In [1]:
import numpy as np
array1d = np.array([1,2,3])

print(array1d)


[1 2 3]


In [2]:
array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)

[[1 2 3]
 [4 5 6]]


#Array Indexing

In [3]:
array = np.array([10,20,30,40])

print(array[1])

20


#Array Slicing

In [4]:
new_array = np.array([10,20,30,40,50])

print(array[1:4])

[20 30 40]


#Array Manipulation

Reshaping

In [6]:
array = np.arange(6)
reshaped = array.reshape(3,2)
print(reshaped)

[[0 1]
 [2 3]
 [4 5]]


Stacking

In [9]:
a = np.array([1,2])
b = np.array([5,6])

#Vertical
print(np.vstack((a,b)))

#horizontal
print(np.hstack((a,b)))

[[1 2]
 [5 6]]
[1 2 5 6]


#Exercise

Create a 1D NumPy array from a Python list [10,20,30,40].

In [10]:
import numpy as np

array_1D = np.array([10,20,30,40])
print(array_1D)

[10 20 30 40]


Create a 2D NumPy array from a Python list [[1,2],[3,4],[5,6]]

In [12]:
array_2D = np.array([[1,2],[3,4],[5,6]])
print(array_2D)

[[1 2]
 [3 4]
 [5 6]]


Create an array of zeros with shape (3,3).

In [13]:
zeros_arr = np.zeros((3,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Create an array with values from 0 to 99 using np.arange()

In [18]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


Create an array of shape (2,4) filled with ones.

In [19]:
ones_arr = np.ones((2,4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#NumPy_Part 2

In [22]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x+y)

[5 7 9]


Aggregate Functions

In [23]:
fun = np.array([1,2,3,4])
print(np.sum(fun))
print(np.mean(fun))
print(np.std(fun))

10
2.5
1.118033988749895


Matrix Multiplication

In [24]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

print(np.dot(m1,m2))

[[19 22]
 [43 50]]


##Brodcasting

In [25]:
array_1 = np.array([1,2,3])
array_2 = 2
print(array_1 * array_2)

[2 4 6]


In [26]:
shape_threeBYOne = np.array([[1],[2],[3]])
shape_three = np.array([10,20,30])
print(shape_threeBYOne + shape_three)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [39]:
shape_three = np.array([1,2,3])
shape_two = np.array([[10],[20]])
print(shape_three + shape_two)

[[11 12 13]
 [21 22 23]]


##Data Preprocessing

In [40]:
data = np.array([1,2,3,4,5])
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[0.   0.25 0.5  0.75 1.  ]


##Random Sampling

In [42]:
random_data = np.random.rand(5)
print(random_data)

[0.22161391 0.22032507 0.6782073  0.5977604  0.67783944]


##Memory Management

In [48]:
sample = np.array([1,2,3,4])
b = sample[1:4]
print(b)
b[1] = 100
print(sample)

[2 3 4]
[  1   2 100   4]


##Linear Algebra

In [49]:
# 3x + y = 9
# x + 2y = 8
# ax = b

a= np.array([[3,1],[1,2]])
b = np.array([[9],[8]])

result = np.linalg.solve(a,b)
print(result)

[[2.]
 [3.]]
